In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine

with open(".env") as f:
    for line in f:
        if "=" in line:
            k, v = line.strip().split("=", 1)
            os.environ[k] = v

engine = create_engine(
    os.environ["DATABASE_URL"],
    connect_args={"connect_timeout": 10}
)


with engine.connect() as conn:
    print("Connected!")

Connected!

In [2]:
pd.read_sql("""
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public';
""", engine)

                   table_name
0                v_claim_full
1               v_ml_features
2                     v_train
3                      v_test
4           v_agent_dashboard
5            v_high_risk_open
6       aa_employee_questions
7       aa_agent_paused_state
8               support_calls
9           feature_snapshots
10       claim_status_history
11                   app_logs
12         agent_interactions
13          model_predictions
14      intervention_outcomes
15                test_claims
16  test_claim_status_history
17                 test_users
18              test_app_logs
19         test_support_calls
20     test_feature_snapshots
21               users_backup
22        aa_agent_tool_calls
23          aa_ml_predictions
24              aa_agent_runs
25   aa_agent_reasoning_steps
26         aa_employee_alerts
27         aa_customer_emails
28  aa_customer_notifications
29                      users
30     aa_scheduled_callbacks
31           aa_interventions
32            aa_agent_errors
33           treatment_master
34                     claims

In [22]:
try:
    df = pd.read_sql("SELECT * FROM model_predictions", engine)
    print(df.head())  # Display the first few rows of the DataFrame
    print("Data fetched from database successfully.")
except Exception as e:
    print(f"Failed to connect to database: {e}")
    print("Loading data from local CSV file instead.")
    # Assuming the CSV is in the data directory relative to the script

   prediction_id  snapshot_id      claim_id    user_id  \
0            226            1  TSTCLM000001  TSTU00001
1            227            2  TSTCLM000002  TSTU00002
2            228            3  TSTCLM000003  TSTU00003
3            229            4  TSTCLM000004  TSTU00004
4            230            5  TSTCLM000005  TSTU00005

                predicted_at  escalation_score risk_level model_version  \
0 2026-03-24 20:24:04.760281          0.315462        low        xgb_v1
1 2026-03-24 20:24:04.760281          0.430938        low        xgb_v1
2 2026-03-24 20:24:04.760281          0.323756        low        xgb_v1
3 2026-03-24 20:24:04.760281          0.315462        low        xgb_v1
4 2026-03-24 20:24:04.760281          0.320549        low        xgb_v1

      top_feature_1           top_feature_2           top_feature_3
0   login_count_48h        status_views_24h  missing_documents_flag
1  adjudicator_flag         login_count_48h        status_views_24h
2   login_count_48h  missing_documents_flag        status_views_24h
3   login_count_48h        status_views_24h  missing_documents_flag
4   login_count_48h        status_views_24h  missing_documents_flag
Data fetched from database successfully.

In [18]:
pd.options.display.max_columns = None

In [25]:
df.head

<bound method NDFrame.head of     prediction_id  snapshot_id      claim_id    user_id  \
0             226            1  TSTCLM000001  TSTU00001
1             227            2  TSTCLM000002  TSTU00002
2             228            3  TSTCLM000003  TSTU00003
3             229            4  TSTCLM000004  TSTU00004
4             230            5  TSTCLM000005  TSTU00005
..            ...          ...           ...        ...
70            296           71  TSTCLM000071  TSTU00071
71            297           72  TSTCLM000072  TSTU00072
72            298           73  TSTCLM000073  TSTU00073
73            299           74  TSTCLM000074  TSTU00074
74            300           75  TSTCLM000075  TSTU00075

                 predicted_at  escalation_score risk_level model_version  \
0  2026-03-24 20:24:04.760281          0.315462        low        xgb_v1
1  2026-03-24 20:24:04.760281          0.430938        low        xgb_v1
2  2026-03-24 20:24:04.760281          0.323756        low        xgb_v1
3  2026-03-24 20:24:04.760281          0.315462        low        xgb_v1
4  2026-03-24 20:24:04.760281          0.320549        low        xgb_v1
..                        ...               ...        ...           ...
70 2026-03-24 20:24:04.763281          0.390725        low        xgb_v1
71 2026-03-24 20:24:04.763281          0.401708        low        xgb_v1
72 2026-03-24 20:24:04.763281          0.401708        low        xgb_v1
73 2026-03-24 20:24:04.763281          0.403486        low        xgb_v1
74 2026-03-24 20:24:04.763281          0.363413        low        xgb_v1

             top_feature_1           top_feature_2           top_feature_3
0          login_count_48h        status_views_24h  missing_documents_flag
1         adjudicator_flag         login_count_48h        status_views_24h
2          login_count_48h  missing_documents_flag        status_views_24h
3          login_count_48h        status_views_24h  missing_documents_flag
4          login_count_48h        status_views_24h  missing_documents_flag
..                     ...                     ...                     ...
70  missing_documents_flag     relative_claim_cost     claim_rejected_flag
71        status_views_24h         login_count_48h  missing_documents_flag
72        status_views_24h         login_count_48h  missing_documents_flag
73        status_views_24h         login_count_48h  missing_documents_flag
74         login_count_48h     relative_claim_cost  missing_documents_flag

[75 rows x 11 columns]>

In [15]:
df2 = pd.read_csv(r"D:\NCI and visa\Academics\semester 2\laya\Complete repo\laya-foresight\ML_pipeline\test_data\test_data_processsed\encoded_test_users_data.csv")

In [27]:
df.head(20)

,prediction_id,snapshot_id,claim_id,user_id,predicted_at,escalation_score,risk_level,model_version,top_feature_1,top_feature_2,top_feature_3
0,226,1,TSTCLM000001,TSTU00001,2026-03-24 20:24:04.760281,0.315462,low,xgb_v1,login_count_48h,status_views_24h,missing_documents_flag
1,227,2,TSTCLM000002,TSTU00002,2026-03-24 20:24:04.760281,0.430938,low,xgb_v1,adjudicator_flag,login_count_48h,status_views_24h
2,228,3,TSTCLM000003,TSTU00003,2026-03-24 20:24:04.760281,0.323756,low,xgb_v1,login_count_48h,missing_documents_flag,status_views_24h
3,229,4,TSTCLM000004,TSTU00004,2026-03-24 20:24:04.760281,0.315462,low,xgb_v1,login_count_48h,status_views_24h,missing_documents_flag
4,230,5,TSTCLM000005,TSTU00005,2026-03-24 20:24:04.760281,0.320549,low,xgb_v1,login_count_48h,status_views_24h,missing_documents_flag
5,231,6,TSTCLM000006,TSTU00006,2026-03-24 20:24:04.760281,0.633931,high,xgb_v1,claim_rejected_flag,missing_documents_flag,login_count_48h
6,232,7,TSTCLM000007,TSTU00007,2026-03-24 20:24:04.760281,0.607753,high,xgb_v1,claim_rejected_flag,missing_documents_flag,login_count_48h
7,233,8,TSTCLM000008,TSTU00008,2026-03-24 20:24:04.761282,0.715773,high,xgb_v1,claim_rejected_flag,missing_documents_flag,adjudicator_flag
8,234,9,TSTCLM000009,TSTU00009,2026-03-24 20:24:04.761282,0.637115,high,xgb_v1,claim_rejected_flag,missing_documents_flag,login_count_48h
9,235,10,TSTCLM000010,TSTU00010,2026-03-24 20:24:04.761282,0.606746,high,xgb_v1,claim_rejected_flag,missing_documents_flag,login_count_48h
10,236,11,TSTCLM000011,TSTU00011,2026-03-24 20:24:04.761282,0.397378,low,xgb_v1,status_views_24h,login_count_48h,missing_documents_flag
11,237,12,TSTCLM000012,TSTU00012,2026-03-24 20:24:04.761282,0.330183,low,xgb_v1,login_count_48h,status_views_24h,missing_documents_flag
12,238,13,TSTCLM000013,TSTU00013,2026-03-24 20:24:04.761282,0.367890,low,xgb_v1,login_count_48h,missing_documents_flag,login_count_24h
13,239,14,TSTCLM000014,TSTU00014,2026-03-24 20:24:04.761282,0.352306,low,xgb_v1,login_count_48h,missing_documents_flag,claim_rejected_flag
14,240,15,TSTCLM000015,TSTU00015,2026-03-24 20:24:04.761282,0.330183,low,xgb_v1,login_count_48h,status_views_24h,missing_documents_flag
15,241,16,TSTCLM000016,TSTU00016,2026-03-24 20:24:04.761282,0.400672,low,xgb_v1,membership_tenure_years,adjudicator_flag,login_count_48h
16,242,17,TSTCLM000017,TSTU00017,2026-03-24 20:24:04.761282,0.576878,high,xgb_v1,adjudicator_flag,relative_claim_cost,login_count_48h
17,243,18,TSTCLM000018,TSTU00018,2026-03-24 20:24:04.761282,0.642846,high,xgb_v1,adjudicator_flag,relative_claim_cost,login_count_48h
18,244,19,TSTCLM000019,TSTU00019,2026-03-24 20:24:04.761282,0.441949,low,xgb_v1,membership_tenure_years,adjudicator_flag,relative_claim_cost
19,245,20,TSTCLM000020,TSTU00020,2026-03-24 20:24:04.761282,0.581610,high,xgb_v1,adjudicator_flag,relative_claim_cost,login_count_48h